name: app_capital_tours
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  fluttertoast: ^8.2.1
  localstore: ^1.3.5
  intl: ^0.18.0
  flutter_map: ^5.0.0
  http: ^1.1.0
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  google_places_flutter: ^2.0.6
  mapbox_gl: ^0.16.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/